version: "3"

services:
  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000  
    environment:
      REDIS_HOST: redis  
    depends_on:
      - redis