version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: codecake_mysql
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root      

  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:5000
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

volumes:
  db-data: